import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.jsx'

// Registers the PWA service worker generated by vite-plugin-pwa so the app
// (and the flag images/data it needs) works offline after the first visit.
registerSW({ immediate: true })

// Mounts the React app into the single <div id="root"> in index.html.
createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
